name: Fly Deploy
on:
  push:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup gcloud credentials
          run: echo "$GCLOUD_CREDENTIALS" >> ethernal-95a14-19f78a7e26cc.json
          shell: bash
          env:
            GCLOUD_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIALS }}
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy . -c fly.toml --remote-only --build-arg NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }} --build-arg NEW_RELIC_APP_NAME=${{ secrets.NEW_RELIC_APP_NAME }}