name: Hosted Hardhat

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
    steps:
      - name: Setup tunnel
        uses: vmactions/ngrok-tunnel@v0.0.1
        with:
          protocol: tcp
          port: 22

      - uses: actions/setup-node@v1
        with:
          node-version: 17.1.0

      - name: Install deps
        run: |
          npm install hardhat -g

      - name: Run hardhat node
        run: |
          npx hardhat node --host 0.0.0.0 --port 8545 &

 