name: SH

on:
  release:
    types: [ published ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install deps
        run: yarn
        
      - name: Build
        run: yarn build
      
      - name: Push
        run: |
          git config --local user.email "adechevigne@gmail.com"
          git config --local user.name "antoinedc"
          git remote add github https://antoinedc:${{ secrets.GITHUB_TOKEN }}@github.com/tryethernal/ethernal-sh.git
          git add dist/ -f
          git add functions/ -f
          git commit -m "Update" -a
          git push github HEAD:master -f
