name: SH

on:
  release:
    types: [ published ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install deps
        run: yarn
        
      - name: Build
        run: yarn build
      
      - name: Push
        run: |
          git config --local user.email "adechevigne@gmail.com"
          git config --local user.name "Antoine"
          git fetch origin
          git branch -u origin/master master
          git remote set-head origin -a
          
          git add dist/ -f
          git add functions/ -f
          git commit -m "Update" -a
          git push origin master -f
