name: SH

on:
  release:
    types: [ published ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install deps
        run: yarn
        
      - name: Build
        run: yarn build
      
      - name: Commit
        run: |
          git config --local user.email "antoine@tryethernal.com"
          git config --local user.name "Antoine"
          git add dist/
          git add functions/
          git commit -m "Update" -a

      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.SH_GITHUB_TOKEN }}
          repository: 'tryethernal/ethernal-sh'
          
